import {
	MaterialDynamicColors,
	SchemeContent,
	SchemeExpressive,
	SchemeFidelity,
	SchemeFruitSalad,
	SchemeMonochrome,
	SchemeNeutral,
	SchemeRainbow,
	SchemeTonalSpot,
	SchemeVibrant,
} from '@material/material-color-utilities';
import { IScheme } from '../interfaces/Scheme';

export const materialDynamicColors: (keyof typeof MaterialDynamicColors)[] = [
	'primary',
	'onPrimary',
	'primaryContainer',
	'onPrimaryContainer',
	'primaryPaletteKeyColor',
	'inversePrimary',
	'primaryFixed',
	'primaryFixedDim',
	'onPrimaryFixed',
	'onPrimaryFixedVariant',
	'secondary',
	'onSecondary',
	'secondaryContainer',
	'onSecondaryContainer',
	'secondaryPaletteKeyColor',
	'secondaryFixed',
	'secondaryFixedDim',
	'onSecondaryFixed',
	'onSecondaryFixedVariant',
	'tertiary',
	'onTertiary',
	'tertiaryContainer',
	'onTertiaryContainer',
	'tertiaryPaletteKeyColor',
	'tertiaryFixed',
	'tertiaryFixedDim',
	'onTertiaryFixed',
	'onTertiaryFixedVariant',
	'neutralPaletteKeyColor',
	'neutralVariantPaletteKeyColor',
	'error',
	'onError',
	'errorContainer',
	'onErrorContainer',
	'surface',
	'onSurface',
	'surfaceVariant',
	'onSurfaceVariant',
	'surfaceDim',
	'surfaceBright',
	'surfaceContainerLowest',
	'surfaceContainerLow',
	'surfaceContainer',
	'surfaceContainerHigh',
	'surfaceContainerHighest',
	'inverseSurface',
	'inverseOnSurface',
	'surfaceTint',
	'outline',
	'outlineVariant',
	'shadow',
	'scrim',
];

export const semanticColors: Record<string, string> = {
	warning: '#ffa600',
	success: '#43a047',
	info: '#039be5',
	energyGridConsumption: '#488fc2',
	energyGridReturn: '#8353d1',
	energySolar: '#ff9800',
	energyNonFossil: '#0f9d58',
	energyBatteryOut: '#4db6ac',
	energyBatteryIn: '#f06292',
	energyGas: '#8e021b',
	energyWater: '#00bcd4',
	red: '#f44336',
	pink: '#e91e63',
	purple: '#926bc7',
	deepPurple: '#6e41ab',
	indigo: '#3f51b5',
	blue: '#2196f3',
	lightBlue: '#03a9f4',
	cyan: '#00bcd4',
	teal: '#009688',
	green: '#4caf50',
	lightGreen: '#8bc34a',
	lime: '#cddc39',
	yellow: '#ffeb3b',
	amber: '#ffc107',
	orange: '#ff9800',
	deepOrange: '#ff6f22',
	brown: '#795548',
	lightGrey: '#bdbdbd',
	grey: '#9e9e9e',
	darkGrey: '#606060',
	blueGrey: '#607d8b',
};

export const paletteColors: string[] = [
	'primary',
	// 'neutral',
	'orange',
	'red',
	'green',
];

export const schemes: IScheme[] = [
	{
		value: 'tonalspot',
		label: 'Tonal Spot',
		class: SchemeTonalSpot,
	},
	{
		value: 'content',
		label: 'Content',
		class: SchemeContent,
	},
	{
		value: 'fidelity',
		label: 'Fidelity',
		class: SchemeFidelity,
	},
	{
		value: 'expressive',
		label: 'Expressive',
		class: SchemeExpressive,
	},
	{
		value: 'fruitsalad',
		label: 'Fruit Salad',
		class: SchemeFruitSalad,
	},
	{
		value: 'rainbow',
		label: 'Rainbow',
		class: SchemeRainbow,
	},
	{
		value: 'vibrant',
		label: 'Vibrant',
		class: SchemeVibrant,
	},
	{
		value: 'neutral',
		label: 'Neutral',
		class: SchemeNeutral,
	},
	{
		value: 'monochrome',
		label: 'Monochrome',
		class: SchemeMonochrome,
	},
];
