import {
	MaterialDynamicColors,
	SchemeContent,
	SchemeExpressive,
	SchemeFidelity,
	SchemeFruitSalad,
	SchemeMonochrome,
	SchemeNeutral,
	SchemeRainbow,
	SchemeTonalSpot,
	SchemeVibrant,
} from '@material/material-color-utilities';
import { IScheme } from '../interfaces/Scheme';

export const materialDynamicColors: (keyof typeof MaterialDynamicColors)[] = [
	'primary',
	'onPrimary',
	'primaryContainer',
	'onPrimaryContainer',
	'primaryPaletteKeyColor',
	'inversePrimary',
	'primaryFixed',
	'primaryFixedDim',
	'onPrimaryFixed',
	'onPrimaryFixedVariant',
	'secondary',
	'onSecondary',
	'secondaryContainer',
	'onSecondaryContainer',
	'secondaryPaletteKeyColor',
	'secondaryFixed',
	'secondaryFixedDim',
	'onSecondaryFixed',
	'onSecondaryFixedVariant',
	'tertiary',
	'onTertiary',
	'tertiaryContainer',
	'onTertiaryContainer',
	'tertiaryPaletteKeyColor',
	'tertiaryFixed',
	'tertiaryFixedDim',
	'onTertiaryFixed',
	'onTertiaryFixedVariant',
	'neutralPaletteKeyColor',
	'neutralVariantPaletteKeyColor',
	'error',
	'onError',
	'errorContainer',
	'onErrorContainer',
	'surface',
	'onSurface',
	'surfaceVariant',
	'onSurfaceVariant',
	'surfaceDim',
	'surfaceBright',
	'surfaceContainerLowest',
	'surfaceContainerLow',
	'surfaceContainer',
	'surfaceContainerHigh',
	'surfaceContainerHighest',
	'inverseSurface',
	'inverseOnSurface',
	'surfaceTint',
	'outline',
	'outlineVariant',
	'shadow',
	'scrim',
];

export const semanticColors: Record<string, string> = {
	warning: '#ffa600',
	success: '#43a047',
	info: '#039be5',
	energyGridConsumption: '#488fc2',
	energyGridReturn: '#8353d1',
	energySolar: '#ff9800',
	energyNonFossil: '#0f9d58',
	energyBatteryOut: '#4db6ac',
	energyBatteryIn: '#f06292',
	energyGas: '#8e021b',
	energyWater: '#00bcd4',
	red: '#FF5252',
	pink: '#FF4081',
	purple: '#E040FB',
	deepPurple: '#7C4DFF',
	indigo: '#536DFE',
	blue: '#448AFF',
	lightBlue: '#40C4FF',
	cyan: '#18FFFF',
	teal: '#64FFDA',
	green: '#69F0AE',
	lightGreen: '#B2FF59',
	lime: '#EEFF41',
	yellow: '#FFFF00',
	amber: '#FFD740',
	orange: '#FFAB40',
	deepOrange: '#FF6E40',
	brown: '#8D6E63',
	lightGrey: '#E0E0E0',
	grey: '#9E9E9E',
	darkGrey: '#616161',
	blueGrey: '#90A4AE',
};

export const paletteColors: string[] = [
	'primary',
	// 'neutral',
	'orange',
	'red',
	'green',
];

export const schemes: IScheme[] = [
	{
		value: 'tonalspot',
		label: 'Tonal Spot',
		class: SchemeTonalSpot,
	},
	{
		value: 'content',
		label: 'Content',
		class: SchemeContent,
	},
	{
		value: 'fidelity',
		label: 'Fidelity',
		class: SchemeFidelity,
	},
	{
		value: 'expressive',
		label: 'Expressive',
		class: SchemeExpressive,
	},
	{
		value: 'fruitsalad',
		label: 'Fruit Salad',
		class: SchemeFruitSalad,
	},
	{
		value: 'rainbow',
		label: 'Rainbow',
		class: SchemeRainbow,
	},
	{
		value: 'vibrant',
		label: 'Vibrant',
		class: SchemeVibrant,
	},
	{
		value: 'neutral',
		label: 'Neutral',
		class: SchemeNeutral,
	},
	{
		value: 'monochrome',
		label: 'Monochrome',
		class: SchemeMonochrome,
	},
];
